### PR TITLE
Support for Entity Framework 7

### PR DESCRIPTION
**Pull request by aivascu**
### Changes

- Adds Entity Framework 7 support
- Adds .NET tools manifest
- Adds NUKE as a .NET tool

### CODE REVIEW

**Comment by berubejp** [comment]
Hi Andrei, first thanks for this library :) Do you expect this PR (EF7 support) to be release soon?

**Comment by aivascu** [comment]
Hi @berubejp,
This PR only adds tests to check that the library works fine with EF7 as is.
Do you experience any issues with the EF7 while testing?

**Comment by aivascu** [comment]
The latest patch was published.

**Comment by berubejp** [comment]
Thanks for the release.

I found my issue.

I only had a dependency on Microsoft.EntityFrameworkCore and EntityFrameworkCore.AutoFixture but not directly on Microsoft.EntityFrameworkCore.Sqlite. So I was using EF7 but since EntityFrameworkCore.AutoFixture has a dependency on Microsoft.EntityFrameworkCore.Sqlite 6, EF.Sqlite 6 was used and it was not working. I forced the dependency for EF Sqlite 7 and everything is fine.

**Pull request merged**
